#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-immutables
Version  : 0.17
Release  : 2
URL      : https://files.pythonhosted.org/packages/64/4a/dc9d9669807d7639f3b25a776accf2226278184aa419dd3bfb042df07f49/immutables-0.17.tar.gz
Source0  : https://files.pythonhosted.org/packages/64/4a/dc9d9669807d7639f3b25a776accf2226278184aa419dd3bfb042df07f49/immutables-0.17.tar.gz
Summary  : Immutable Collections
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-immutables-license = %{version}-%{release}
Requires: pypi-immutables-python = %{version}-%{release}
Requires: pypi-immutables-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
immutables
==========
.. image:: https://github.com/MagicStack/immutables/workflows/Tests/badge.svg?branch=master
:target: https://github.com/MagicStack/immutables/actions?query=workflow%3ATests+branch%3Amaster+event%3Apush

%package license
Summary: license components for the pypi-immutables package.
Group: Default

%description license
license components for the pypi-immutables package.


%package python
Summary: python components for the pypi-immutables package.
Group: Default
Requires: pypi-immutables-python3 = %{version}-%{release}

%description python
python components for the pypi-immutables package.


%package python3
Summary: python3 components for the pypi-immutables package.
Group: Default
Requires: python3-core
Provides: pypi(immutables)

%description python3
python3 components for the pypi-immutables package.


%prep
%setup -q -n immutables-0.17
cd %{_builddir}/immutables-0.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648353418
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-immutables
cp %{_builddir}/immutables-0.17/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-immutables/ad35a1f361b4d6c956a59710f3b88965da9d0792
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-immutables/ad35a1f361b4d6c956a59710f3b88965da9d0792

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
